import asyncio

from fastapi import APIRouter

from bot import ai_brain, news

router = APIRouter(prefix="/news", tags=["news"])


@router.get("/feed")
async def feed():
    """Latest aggregated forex/crypto headlines (newest-first, images stripped)."""
    stories = await news.get_news()
    return {"stories": stories, "updated_at": news.news_updated_at()}


@router.get("/telegram")
async def telegram():
    """Latest posts from the configured public Telegram channels."""
    posts = await news.get_telegram()
    return {"posts": posts, "updated_at": news.telegram_updated_at()}


@router.get("/calendar")
async def calendar():
    """This week's economic calendar (ForexFactory feed): currency, impact, forecast, previous."""
    events = await news.get_calendar()
    return {"events": events, "updated_at": news.calendar_updated_at()}


@router.get("/brief")
async def brief(refresh: bool = False):
    """AI pre-market brief built from today's headlines.

    Cached: a plain GET returns the last brief without calling the AI, `refresh=true`
    regenerates it (that's the one that spends provider tokens). Generated by Gemini,
    falling back to Claude.
    """
    if refresh and not ai_brain.available():
        # Say so plainly rather than returning a stale brief as if it were fresh.
        return {
            "brief": await news.brief_from_cache(),
            "error": ("No AI provider is configured. Set GEMINI_API_KEY in .env "
                      "(or ANTHROPIC_API_KEY / the Claude Code CLI) and restart the backend."),
        }
    data = await news.get_brief(force=refresh) if refresh else await news.brief_from_cache()
    if data is None and not refresh:
        return {"brief": None, "never_generated": True}
    return {"brief": data}


@router.get("/all")
async def all_():
    """News + calendar in one round-trip (what the dashboard polls)."""
    stories, events, posts = await asyncio.gather(
        news.get_news(), news.get_calendar(), news.get_telegram())
    return {
        "stories": stories,
        "events": events,
        "telegram": posts,
        "news_updated_at": news.news_updated_at(),
        "calendar_updated_at": news.calendar_updated_at(),
        "telegram_updated_at": news.telegram_updated_at(),
    }
